Accounting/urls.py
from django.urls import path
from Accounting import views

app_name ='accounting'
urlpatterns=[
  
    path('record_list/',views.record_list,name="record_list"),
    path('record_details/<int:record_id>/',views.record_details,name='record_details'),
    path('record_register/',views.record_register,name='record_register'),
    path('project_register/',views.project_register,name='project_register'),
    path('projects_list/',views.projects_list,name='projects_list'),
    path('about/',views.about_us,name='about_us'),
    path('project_details/<int:project_id>',views.project_details,name='project_details'),
    path('project_edit/<int:project_edit_id>',views.project_edit,name='project_edit'),
    path('record_edit/<int:record_edit_id>/',views.record_edit,name='record_edit')


] 

profiles/urls.py
from django.urls import path
from profiles import views

app_name ='accounts'
urlpatterns=[
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),

]

pymankar/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

from Accounting import views
app_name ='pymankar'
urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounting/',include('Accounting.urls')),
    path('accounts/',include('profiles.urls'))
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Accounting/models.py
from django.db import models

from django.db.models import F
class AnnotationManager(models.Manager):

    def __init__(self, **kwargs):
        super().__init__()
        self.annotations = kwargs

    def get_queryset(self):
        return super().get_queryset().annotate(**self.annotations)


class recording(models.Model):
    
    class Meta:

        verbose_name="ثبت دخل و خرج"
        verbose_name_plural="ثبت دخل و خرج"
    
    EXPENSE='1'
    INCOME='2'

    types_choice=(
        (EXPENSE,'خرج کرد'),
        (INCOME,'درآمد')
    )

    types=models.CharField('نوع',choices=types_choice,max_length=10)
    project=models.ForeignKey('Project',on_delete=models.PROTECT,verbose_name='نام پروژه',null=True)
    title=models.CharField('عنوان',max_length=100)
    amount=models.BigIntegerField('تعداد')
    unit_price=models.BigIntegerField('مبلغ واحد')
    # total_price=models.BigIntegerField('مبلغ کل')
    
    date=models.DateField('تاریخ',null=True,blank=True)
    description=models.TextField('توضیحات',null=True,blank=True)

    _total_price=None

    objects = AnnotationManager(

        total_price=F('amount') * F('unit_price')
    )



    def __str__(self):
        return '{}    {}  {}' .format(self.title,self.total_price,self.date)


class Project(models.Model):

    class Meta:
        verbose_name="پروژه"
        verbose_name_plural="پروژه ها"

    status_choise=[
        ('1','در دست اجرا'),
        ('2','پیش نویس'),
        ('3','تحویل موقت'),
        ('4','تحویل قطعی'),
        ('5','تعلیق')
    ]

    name=models.CharField('عنوان پروژه', max_length=50)
    number=models.CharField('شماره قرارداد',max_length=50,null=True,blank=True)
    date=models.DateField('تاریخ قرارداد',null=True,blank=True)
    cost=models.BigIntegerField('مبلغ قرارداد',null=True,blank=True)
    master=models.CharField('نام کارفرما ',max_length=50,null=True,blank=True)
    status=models.CharField('وضعیت قرارداد',choices=status_choise,null=True,blank=True,max_length=15)
    
    
    def __str__(self):
        return '{}'.format(self.name)

Accounting/forms.py
from django import forms
from Accounting.models import Project,recording
from django.core.exceptions import ValidationError

class SearchForm(forms.Form):

    NOTING=None
    EXPENSE='1'
    INCOME='2'

    types_choice=(
        
        (EXPENSE,'خرج کرد'),
        
        (INCOME,'درآمد'),
        (NOTING,'-----')
        
    )



    record_name=forms.CharField(label='عنوان',required=False)
    project_name=forms.ModelChoiceField(label='نام پروژه',
                queryset=Project.objects.all(),required=False)
    max_price=forms.IntegerField(label='بیشترین قیمت',min_value=0,required=False)
    min_price=forms.IntegerField(label='کمترین قیمت',min_value=0,required=False)
    type_of=forms.ChoiceField(label='نوع',choices=types_choice)
                               


class RegisterRecordForm(forms.ModelForm):
    class Meta:
        model=recording
        exclude=[]
        

    # def clean_unit_price(self):
    #     unit_price=self.cleaned_data.get('unit_price')
    #     if unit_price % 1000 != 0:
    #         raise ValidationError('مقداردرست نیست')
    #     else:
    #         return unit_price


class ProjectForm(forms.ModelForm):
    class Meta:
        model=Project
        exclude=[]

Accounting/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect,HttpResponse
from Accounting.models import recording,Project
from django.urls import reverse
from Accounting.forms import SearchForm,RegisterRecordForm,ProjectForm
from django.db.models import  Sum,Avg
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

def home(request):
    return render(request,"html/home_page.html")


@login_required
def record_list(request):
    search_form=SearchForm(request.GET)

    records=recording.objects.filter(types='1')
    expense_sum=records.aggregate(jam=Sum('total_price'))
    expense_sum=list(expense_sum.values())[0]

    records=recording.objects.filter(types='2')
    income_sum=records.aggregate(jam=Sum('total_price'))
    income_sum=list(income_sum.values())[0]
    
    
    records=recording.objects.all()

    if search_form.is_valid():
        
        

        records=records.filter(title__contains=search_form.cleaned_data['record_name'])
        if search_form.cleaned_data['type_of'] is not None :
            records=records.filter(types=search_form.cleaned_data['type_of'])
        if search_form.cleaned_data['project_name'] is not None:
            records=records.filter(project=search_form.cleaned_data['project_name'])
        if search_form.cleaned_data['max_price'] is not None:
            records=records.filter(total_price__lte =search_form.cleaned_data['max_price'])
        if search_form.cleaned_data['min_price'] is not None:
            records=records.filter(total_price__gte =search_form.cleaned_data['min_price'])


        

   
    context={
        'records':records,
        'search_form':search_form,
        'expense_sum':expense_sum,
        'income_sum':income_sum
    }
    return render(request,'html/record_list.html',context)

def record_details(request,record_id):
    
    record=get_object_or_404(recording,pk=record_id)
    context={
        'record':record

    }
    return render(request,'html/record_details.html',context)


def record_register(request):

    if request.method == 'POST':
        record_form=RegisterRecordForm(request.POST)
        if record_form.is_valid():
            record_form.save()

            return HttpResponseRedirect(reverse('accounting:record_list'))
    else:
        record_form=RegisterRecordForm()

    context={
        'record_form' : record_form
    }
    return render(request,'html/record_register.html',context)

def record_edit(request,record_edit_id):

    record=recording.objects.get(id=record_edit_id)
    if request.method == "POST" :
         edit_form=RegisterRecordForm(request.POST,instance=record)
         if edit_form.is_valid():
             edit_form.save()
             
             return HttpResponseRedirect(reverse('accounting:record_details', args=(record.id,) ))
    else:
        edit_form=RegisterRecordForm(instance=record)


    context={
        'edit_form' :  edit_form
    }

    return render(request,'html/edit_record.html',context)

def project_register(request):
    
    if request.method == 'POST':
        project=ProjectForm(request.POST)
        if project.is_valid():
            project.save()
            return HttpResponseRedirect(reverse('accounting:record_list'))
    else:
        project=ProjectForm()

    context={
        'project':project
    }
    return render(request,'html/register_project.html',context)

def projects_list(request):
    projects=Project.objects.all()
    context={
        'projects':projects
    }

    return render(request,'html/projects_list.html',context)

def project_details(request,project_id):

    projects=get_object_or_404(Project,id=project_id)
    context={
        'projects':projects
    }
    return render(request,'html/project_details.html',context)

def project_edit(request,project_edit_id):
    
    project=Project.objects.get(id=project_edit_id)
    if request.method == 'POST':
            project_form=ProjectForm(request.POST,instance=project)
            if project_form.is_valid():
                project_form.save()
                return HttpResponseRedirect(reverse('accounting:project_details', args=(project.id,) ))
    else:


        project_form=ProjectForm(instance=project)

    context={
        'project_form':project_form
    }
    return render(request,'html/project_edit.html/',context)

def about_us(request):

    return render(request,'html/about_us.html/')

def login(request):
    return HttpResponse('hello')    

Accounting/templates/html/_form_field.html
<div class="col-3">
    <small class="text-muted">
        {{field.label}}
    </small>
</div>
<div class="col-9">


{{field}}
</div>
<div class="w-100 my-1"></div>

Accounting/templates/html/_models_field.html
<div class="col-3">
    <small class="text-muted">
        {{ field}}
    </small>
</div>
<div class="col-9">
    {{ field }}
</div>
<div class="w-100 my-1"></div>

Accounting/templates/html/about_us.html
{% extends  "html/base.html" %}
{% load static %}

{% block title %} 
درباره ما

{% endblock %}

{% block toolbar_title %}

درباره ما

{% endblock %}

{% block main_content %}

هدف از این سامانه ارائه راه حلی جامه در زمینه حسابداری ، امور بیمه
و مدیریت پروژه های پیمانکاری به کلیه پیمانکاران و فعالین در سایر زمینه های مرتبط است
این سایت در حال حاضر در مرحله آزمایشی قرارداد 
جهت هرگونه پیشنهاد با ایمیل زیر تماس بگیرید.
<br>s
kazem3d@gmail

{% endblock %}

Accounting/templates/html/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="fa_IR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>

  <!-- <link rel="stylesheet" type="text/css" href="{% static "/accounting/css/bootstrap.css" %}"> -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
             integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
             crossorigin="anonymous">
  <!-- <link rel="stylesheet" type="text/css" href="{% static "/accounting/css/font-awesome.css" %}"> -->
  <link rel="stylesheet" type="text/css" href="{% static "/accounting/css/main.css" %}">

</head>
<body dir="rtl">

<div class="container" id="container">

    <div class="row align-items-center" id="header">
        <div class="col text-center">
            <h2>
                داشبورد پیمانکاران
            </h2>
            
        </div>
    
    </div>

  <div class="row align-items-center" id="toolbar">
            <div class="col-6">
                <h4>
                    {% block toolbar_title %}{% endblock %}
                </h4>
            </div>
        <div class="col-6 text-left">
                <a class="btn btn-light py-1 px-2" href="/" >
                    <i class="fas fa-film"></i>
                    خانه
                </a>
                <a class="btn btn-success py-1 px-2" href={% url 'accounting:about_us' %}>
                    <i class="fas fa-ticket-alt"></i>
                        درباره ما
                </a>
   
                     
                {% if user.is_authenticated %}

                    

                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{user.get_full_name}}
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item" href="#">مشاهده پروفایل</a>
                      <a class="dropdown-item" href={% url 'accounts:logout' %}>خروج</a>
                    </div>
                </div>
                {% else %}

                <div class="dropdown">
                    <a class="btn btn-secondary " href={% url 'accounts:login' %}   >
                        ورود
                    </a>

                </div>


                {% endif %}


                {% block toolbar_buttons %}
                <!-- <a class="btn btn-light py-1 px-2" href={% url 'accounting:record_list' %} >
                    <i class="fas fa-building"></i>
                    لیست رکوردها
                </a>
                <a class="btn btn-light py-1 px-2" href={% url 'accounting:record_register' %} >
                    <i class="fas fa-building"></i>
                    ثبت رکورد
                </a> -->
                
                {%endblock%}
        </div>
       
    </div>

               





    {% block main_content %}{% endblock %}
  
    <div class="row align-content-center" id="footer">
        <div class="col text-center">
            <span>
                ما را در شبکه‌های اجتماعی دنبال کنید.

                
                <a class="social-media-icon" href="#">
                    <i class="fab fa-twitter"></i>
                </a>
                <a class="social-media-icon" href="#">
                    <i class="fab fa-instagram"></i>
                </a>
                <a class="social-media-icon" href="#">
                    <i class="fab fa-telegram-plane"></i>
                </a>
            </span>
        </div>
    </div>

    





</div>



  


  
  <!-- <script src="{% static "/accounting/js/jquery-3.4.0.min.js" %}"></script> -->
  <!-- <script src="{% static "/accounting/js/bootstrap.bundle.js" %}"></script> -->
  
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" 
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" 
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" 
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" 
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" 
            crossorigin="anonymous"></script>
  
  <script src="{% static "/accounting/js/font-awesome.js" %}"></script>
  <script src="{% static "/accounting/js/main.js" %}"></script>
</body>
</html>

Accounting/templates/html/edit_record.html
{% extends  "html/base.html" %}


{% load static %}
{% load humanize %}



{% block title %}
  {{record.title}}
{% endblock %}

{% block toolbar_title %}
ویرایش رکورد
{% endblock %}

{% block toolbar_buttons %} 


<a class="btn btn-light py-1 px-2" href={% url 'accounting:record_list' %} >
    <i class="fas fa-building"></i>
    لیست رکوردها
</a>
                
                
<a class="btn btn-light py-1 px-2" href={% url 'accounting:record_register' %} >
    <i class="fas fa-building"></i>
    ثبت رکورد
</a>


{% endblock %}         



{% block main_content %}
  
<form method="POST" action="">
    {% csrf_token %}
    {{edit_form}}

    <button class="btn btn-danger py-1 px-2" type="submit" %} >
            ثبت ویرایش     
    </button>

</form>
    
  <!-- <div class="row py-3">
    <div class="col-8 item-details">
        <div class="row px-3">
            <div class="col-3">
                <small class="text-muted">
                    عنوان:
                </small>
            </div>
            <div class="col-9">
                {{ edit_form.title }}
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-3">
                <small class="text-muted">
                    تاریخ:
                </small>
            </div>
            <div class="col-9">
                {{ edit_form.date }}
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-3">
                <small class="text-muted">
                    قیمت کل
                </small>
            </div>
            <div class="col-9">
                {{ edit_form.total_price | intcomma:False  }}
                ریال
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-3">
                <small class="text-muted">
                    نام پروژه
                </small>
            </div>
            <div class="col-9 item-text-box">
                {{ edit_form.project }}
            </div>
        </div>
    </div> -->
{% endblock %}
  

Accounting/templates/html/home_page.html
{% extends  "html/base.html" %}
{% load static %}

{% block title %} صفحه اصلی{% endblock %}

{% block toolbar_title %}صفحه اصلی{% endblock %}



{% block main_content %}

<br>
<a class="btn btn-primary btn-lg btn-block py-1 px-2" href={% url 'accounting:record_list' %} >
    <i class="fas fa-building"></i>
    لیست دخل و خرج
</a>
<br>

<a class="btn btn-warning btn-lg btn-block py-1 px-2" href={% url 'accounting:projects_list' %} >
    <i class="fas fa-building"></i>
    لیست پروژها
</a>
<br>
<a class="btn btn-success btn-lg btn-block py-1 px-2" href={% url 'accounting:record_register' %} >
    <i class="fas fa-building"></i>
    ثبت دخل و خرج
</a>
<br>
<a class="btn btn-danger btn-lg btn-block py-1 px-2" href={% url 'accounting:project_register' %} >
    <i class="fas fa-building"></i>
    ثبت پروژه
</a>
<br>
{% endblock %}

Accounting/templates/html/project_details.html
{% extends  "html/base.html" %}


{% load static %}
{% load humanize %}



{% block title %}
  {{record.title}}
{% endblock %}

{% block toolbar_title %}
جزئیات پروژه
{% endblock %}

{% block toolbar_buttons %} 



{% endblock %}         



{% block main_content %}
  

  <div class="row py-3">
    <div class="col-8 item-details">
        <div class="row px-3">
           

            <div class="col-3">
                <small class="text-muted">
                    عنوان:
                </small>
            </div>
            <div class="col-9">
                {{ projects.name }}
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-3">
                <small class="text-muted">
                    تاریخ:
                </small>
            </div>
            <div class="col-9">
                {{ projects.date }}
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-3">
                <small class="text-muted">
                    شماره قرارداد:
                </small>
            </div>
            <div class="col-9">
                {{ projects.number }}
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-3">
                <small class="text-muted">
                مبلغ پروژه
                </small>
            </div>
            <div class="col-9">
                {{ projects.cost | intcomma:False  }}
                ریال
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-3">
                <small class="text-muted">
                    نام کارفرما
                </small>
            </div>
            <div class="col-9 item-text-box">
                {{ projects.master }}
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-3">
                <small class="text-muted">
                    وضعیت قرارداد
                </small>
            </div>
            <div class="col-9">
                {{ projects.get_status_display  }}
            </div>
            <div class="w-100 my-1"></div>

            <a class="btn btn-danger py-1 px-2" href={% url 'accounting:project_edit' project_edit_id=projects.id %} >
                
                ویرایش رکورد
            </a>

        </div>
    </div>
{% endblock %}
  

Accounting/templates/html/project_edit.html
{% extends  "html/base.html" %}


{% load static %}
{% load humanize %}



{% block title %}
  {{record.title}}
{% endblock %}

{% block toolbar_title %}
ویرایش پروژه
{% endblock %}

{% block toolbar_buttons %} 


<a class="btn btn-light py-1 px-2" href={% url 'accounting:projects_list' %} >
    <i class="fas fa-building"></i>
    لیست پروژه ها
</a>
                
                



{% endblock %}         



{% block main_content %}
  
<form method="POST" action="">
    {% csrf_token %}
    {{project_form}}

    <button class="btn btn-danger py-1 px-2" type="submit" %} >
            ثبت ویرایش     
    </button>

</form>
    
  <!-- <div class="row py-3">
    <div class="col-8 item-details">
        <div class="row px-3">
            <div class="col-3">
                <small class="text-muted">
                    عنوان:
                </small>
            </div>
            <div class="col-9">
                {{ edit_form.title }}
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-3">
                <small class="text-muted">
                    تاریخ:
                </small>
            </div>
            <div class="col-9">
                {{ edit_form.date }}
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-3">
                <small class="text-muted">
                    قیمت کل
                </small>
            </div>
            <div class="col-9">
                {{ edit_form.total_price | intcomma:False  }}
                ریال
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-3">
                <small class="text-muted">
                    نام پروژه
                </small>
            </div>
            <div class="col-9 item-text-box">
                {{ edit_form.project }}
            </div>
        </div>
    </div> -->
{% endblock %}
  

Accounting/templates/html/projects_list.html
{% extends  "html/base.html" %}

{% load static %}

{% block title %}
سامانه جامع پیمانکاران
{% endblock %}

{% block toolbar_title %}
لیست پروژه ها
{% endblock %}

{% block main_content %}
  <div class="row">
    <div class="col py-3">
        {% if projects %}
        <ul class="item-list">
            {% for project in projects %}    
                <li>
                    
                        <i class="fas fa-film"></i>
                        <a href={% url 'accounting:project_details' project_id=project.id %}>
                          {{ project.name}}
                         
                        <small class="text-muted">
                           
                        </small>
                       </a>
                    
                </li>
            {% endfor %}
            
        </ul>
        {% else %}
        <div class="alert alert-danger">
            در حال حاضر هیچ پروژه ای برای نمایش وجود ندارد.
        </div>
    </div>
</div>        
    {% endif %}

{% endblock %}

Accounting/templates/html/record_details.html
{% extends  "html/base.html" %}


{% load static %}
{% load humanize %}



{% block title %}
  {{record.title}}
{% endblock %}

{% block toolbar_title %}
جزئیات رکورد
{% endblock %}

{% block toolbar_buttons %} 


<a class="btn btn-light py-1 px-2" href={% url 'accounting:record_list' %} >
    <i class="fas fa-building"></i>
    لیست رکوردها
</a>
                
                
<a class="btn btn-light py-1 px-2" href={% url 'accounting:record_register' %} >
    <i class="fas fa-building"></i>
    ثبت رکورد
</a>


{% endblock %}         



{% block main_content %}
  

  <div class="row py-3">
    <div class="col-8 item-details">
        <div class="row px-3">
            <div class="col-3">
                <small class="text-muted">
                    عنوان:
                </small>
            </div>
            <div class="col-9">
                {{ record.title }}
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-3">
                <small class="text-muted">
                    تاریخ:
                </small>
            </div>
            <div class="col-9">
                {{ record.date }}
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-3">
                <small class="text-muted">
                    قیمت کل
                </small>
            </div>
            <div class="col-9">
                {{ record.total_price | intcomma:False  }}
                ریال
            </div>
            <div class="w-100 my-1"></div>
            <div class="col-3">
                <small class="text-muted">
                    نام پروژه
                </small>
            </div>
            <div class="col-9 item-text-box">
                {{ record.project }}
            </div>
        </div>
    </div>
{% endblock %}
  

Accounting/templates/html/record_list.html
{% extends  "html/base.html" %}

{% load static %}
{% load humanize %}


{% block title %}سامانه جامع پیمانکاران{% endblock %}

{% block toolbar_title %}لیست رکوردها{% endblock %}

{% block toolbar_buttons %}
<a class="btn btn-light py-1 px-2" href={% url 'accounting:record_register' %} >
    <i class="fas fa-building"></i>
    ثبت رکورد
</a>
       
{%endblock%}



{% block main_content %}
  <div class="row">
    <div class="col py-3">
        {% if records %}

        <div class="row ">
            <div class="col my-1 px-3 mx-3 py-2 search-bar">
                <form action="" method="GET" class="form-row px-2">
                    
                    <label for="{{search_form.record_name.id_for_label}}" class="col-2" > {{search_form.record_name.label}}</label>  
                        <div class="col-4">
                            {{search_form.record_name}}
                            {{search_form.record_name.errors}}
                        </div>
                    
                    <label for="{{search_form.project_name.id_for_label}}" class="col-2" > {{search_form.project_name.label}}</label>  
                    <div class="col-4">
                        {{search_form.project_name}}
                        {{search_form.project_name.errors}}
                    </div>

                    <label for="{{search_form.max_price.id_for_label}}" class="col-2" > {{search_form.max_price.label}}</label>  
                    <div class="col-4">
                        
                        <input  type="number" name="max_price" min="0" id="id_max_price">
                      
                        {{search_form.max_price.errors}}
                    </div>

                    <label for="{{search_form.min_price.id_for_label}}" class="col-2" > {{search_form.min_price.label}}</label>  
                    <div class="col-4">
                        {{search_form.min_price}}
                        {{search_form.min_price.errors}}
                    </div>

                    <label for="{{search_form.type_of.id_for_label}}" class="col-2" > {{search_form.type_of.label}}</label>  
                    <div class="col-4">
                        {{search_form.type_of}}
                        {{search_form.type_of.errors}}
                    </div>

                    
                    
                <button type="submit">جستجو</button>   
                </form>

             </div>
    
        </div>


            <ul class="item-list">

                <div class="row px-2">
                    <div class="col">
                        <div class="alert alert-info mt-2 mb-0 py-1 px-3">
                            جمع کل خرج کرد :
                            {{expense_sum | intcomma:False}}
                            ريال
                        </div>
                        
                        <div class="alert alert-info mt-2 mb-0 py-1 px-3">
                            جمع کل درآمد :
                            {{income_sum | intcomma:False}}
                            ريال
                        </div>
                    </div>
                </div>
                <br>

                
                {% for record in records %}
                    <li>
                            
                            <i class="fas fa-film"></i>
                            <a href={%url "accounting:record_details" record_id=record.id  %}>
                              {{ record.title}}
                              :
                              {{record.total_price | intcomma:False}}
                              ریال
                            <small class="text-muted">
                             {{record.date|date:"SHORT_DATE_FORMAT"}}   
                            </small>
                           </a>
                        
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <div class="alert alert-danger">
                در حال حاضر هیچ رکوردی برای نمایش وجود ندارد.
            </div>
        {% endif %}
    </div>
  </div>  

  {% endblock %}

  

Accounting/templates/html/record_register.html
{% extends  "html/base.html" %}

{% load static %}
{% load humanize %}
{% block title %}سامانه جامع پیمانکاران{% endblock %}

{% block toolbar_title %}ثبت رکورد جدید{% endblock %}

{% block toolbar_buttons %}
<a class="btn btn-light py-1 px-2" href={% url 'accounting:record_list' %} >
    <i class="fas fa-building"></i>
    لیست رکوردها
</a>
        
{%endblock%}

{% block main_content %}
<form action="" method="POST"  class="form py-2 ">
    {% csrf_token %}
    <div class="row py-3">
        <div class="col-8 item-details">
            <div class="row px-3">
                {% include 'html/_form_field.html' with field=record_form.project %}
                {% include 'html/_form_field.html' with field=record_form.types %}
                {% include 'html/_form_field.html' with field=record_form.title %}
                {% include 'html/_form_field.html' with field=record_form.amount %}
                {% include 'html/_form_field.html' with field=record_form.unit_price %}
                <div class="col-3">
                    <small class="text-muted">
                        مبلغ کل
                    </small>
                </div>
                <div class="col-9">
                <!-- {{record_form.}} -->
                </div>
                <div class="w-100 my-1"></div>
                <!-- {% include 'html/_form_field.html' with field=record_form.total_price %} -->
                {% include 'html/_form_field.html' with field=record_form.date%}
                {% include 'html/_form_field.html' with field=record_form.description%}

                <button type="submit" class="btn btn-success btn-sm" >
                    ثبت
                </button>

            </div>

        </div>

    </div>

</form>
{%endblock%}